import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeContext";
import ClientThemeWrapper from "@/components/ClientThemeWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="coffee">
      <body
        className={` ${inter.className} grid grid-rows-[auto_1fr_auto] h-screen`}
      >
        <ThemeProvider>
          <ClientThemeWrapper>
            <Navbar />
            {children}
            <Footer />
          </ClientThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
